##
## Source the long term, committed .zshrc File
##

source "$HOME/.zshrc.lts"

##
## Local .zshrc configurations
## Put any machine-specific overrides here that you don't want synced with source control
##

# Anything after end of file is automatically generated by installation scripts
# and should either be moved to earlier sections or deleted using ./setup/cleanup.sh
### End of File ###
