#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# float system prefs
floating_applications="(Spotify|League of Legends|Riot Client|FaceTime|Minecraft Launcher|Steam|DisplayLinkUserAgent|Paradox Launcher|Victoria 3|System Settings)"
yabai -m rule --add app="^$floating_applications$" manage=off

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow float
yabai -m config window_opacity off
yabai -m config window_border on
yabai -m config window_border_width 2
yabai -m config active_window_border_color 0xcc63c8f8
yabai -m config normal_window_border_color 0x00000000
yabai -m config insert_feedback_color 0xE02d74da
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap
yabai -m config window_shadow float
yabai -m config window_border_blur off

# status bar
yabai -m config external_bar all:32:0

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 4
yabai -m config bottom_padding 4
yabai -m config left_padding 4
yabai -m config right_padding 4
yabai -m config window_gap 4

# signals for sketchybar
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 2 && sketchybar --trigger space_change --trigger windows_on_spaces"
yabai -m signal --add event=display_removed action="sleep 1 && sketchybar --trigger space_change --trigger windows_on_spaces"

# added settings
echo "yabai configuration loaded.."
# YABAI_CERT=yabai-cert sh -c "$(curl -fsSL "https://git.io/update-yabai")" &
