#!/bin/bash

source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items"     # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="FiraCode Nerd Font Mono" # Needs to have Regular, Bold, Semibold, Heavy and Black variants

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist >/dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
  height=32
  blur_radius=0
  position=top
  padding_left=5
  padding_right=5
  sticky=on
  color=0x6624273a
  notch_width=0
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color=0xffffffff
  icon.padding_left=8
  icon.padding_right=7
  label.font="$FONT:Bold:12.0"
  label.color=0xffcad3f5
  label.padding_left=0
  label.padding_right=7
  background.height=24
  background.corner_radius=5
  background.padding_left=2
  background.padding_right=2
  background.color=0xff24273a
)

sketchybar --default "${defaults[@]}"

# Left
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Center
source "$ITEM_DIR/spotify.sh"

# Right
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

windows_on_spaces
